#spring:
#  application:
#    name: eureka-server-cluster
#server:
#  port: 8000
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://192.168.10.136:8000/eureka/,http://192.168.10.137:8000/eureka/

#---
#spring:
#  application:
#    name: eureka-server-cluster
#server:
#  port: 8000
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://192.168.10.135:8000/eureka/,http://192.168.10.137:8000/eureka/

#---
spring:
  application:
    name: eureka-server-cluster
server:
  port: 8000
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.10.135:8000/eureka/,http://192.168.10.136:8000/eureka/
