server:
  port: 7005
  servlet:
    context-path: /ug

spring:
  application:
    name: ug
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://mysql.jy.com:3306/db1?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: jyIsTpYmq7%Z
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池配置
    druid:
      initial-size: 50   # 初始化大小
      min-idle: 50       # 最小空闲连接个数
      max-active: 200    # 最大连接个数
      max-wait: 60000   # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 300000    # 配置间隔多久才进行一次监测，监测需要关闭的空闲连接，单位时毫秒
      min-evictable-idle-time-millis: 1800000       # 配置一个连接在池中最小生存的时间
      validation-query: select 'x'                # 用来监测连接是否有效的sql，要求是一个查询语句
      test-while-idle: true            # 建议配置为true，不影响性能，并且保证安全性。如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-on-borrow: false            # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false            # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      pool-prepared-statements: true   # 打开PSCache，并且指定每个连接上PSCache的大小
      max-open-prepared-statements: 20
      aop-patterns: mykine.optdata.demomybatis.* #监控SpringBean
      stat-view-servlet: #监控页面配置
        enabled: true #开启显示监控页面
        login-username: admin    #监控页面登录名
        login-password: admin123 #监控页面登陆密码
        reset-enable: false      #不显示重置按钮
        url-pattern: '/druid/*' #监控页面路径前缀,不要改成其他的，因为有个bug:错误路径访问会统一跳转到固定的地址/druid/login.html
      web-stat-filter: #监控web页面配置
        enabled: true  #开启
        url-pattern: '/*' #监控路径
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*' #要排除的路径
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      filter: #监控详细配置
        stat:
          slow-sql-millis: 500 #设置慢查询限制时间，单位毫秒
          log-slow-sql: true #开启慢查询日志

#配置mybatis规则
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml #配置mybatis全局配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml #配置mybatis的sql映射文件

  kafka:
    bootstrap-servers: 192.168.10.135:9092,192.168.10.136:9092,192.168.10.137:9092
    listener:
      concurrency: 4

eureka:
  client:
    service-url:
      defaultZone: http://192.168.10.135:8000/eureka/,http://192.168.10.136:8000/eureka/,http://192.168.10.137:8000/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

adconf:
  mysql:
    host: 192.168.10.98
    port: 3306
    username: root
    password: jyIsTpYmq7%Z
    binlogName: mysql-bin.000007
    position: 154

  kafka:
    topic: ug-data


jwt:
  key: c21hcnRybS1kZGRzbWFydHJtLWRkZHNtYXJ0cm0tZGRk
  expirationSecs: 2592000

commodity:
  file:
    json:
      path: commodity_new.json

#申明es服务地址
elasticsearch:
  ip: 192.168.10.135:9200